eplus_naming_dict = {
    ('Site Outdoor Air Drybulb Temperature', '*'): "Ambient Temp.",
    ('Site Diffuse Solar Radiation Rate per Area', '*'): "Diffuse Solar Rad.",
    ('Site Direct Solar Radiation Rate per Area', '*'): "Direct Solar Rad.",
    ('Facility Total HVAC Electric Demand Power', '*'): "HVAC Power",
    # ('System Node Temperature', 'VAV SYS 1 OUTLET NODE'): "Sys Out Temp.",
    # ('Heating Coil Electric Power', 'Main Heating Coil 1'): "Heat Coil Power",
    # ('Cooling Coil Electric Power', 'Main Cooling Coil 1'): "Cool Coil Power",
    # ('Occupancy Flag', '*'): "Occupancy Flag",
    # ('System Node Temperature', 'Mixed Air Node 1'): "MA Temp.",
    # ('Indoor Air Temperature Setpoint', '*'): "Indoor Temp. Setpoint",
    # node outputs
    # ('System Node Temperature', 'SPACE1-1 IN NODE'): "In Node Temp Zone 1",
    # ('System Node Temperature', 'SPACE2-1 IN NODE'): "In Node Temp Zone 2",
    # ('System Node Temperature', 'SPACE3-1 IN NODE'): "In Node Temp Zone 3",
    # ('System Node Temperature', 'SPACE4-1 IN NODE'): "In Node Temp Zone 4",
    # ('System Node Temperature', 'SPACE5-1 IN NODE'): "In Node Temp Zone 5",
    #
    # ('System Node Mass Flow Rate', 'SPACE1-1 IN NODE'): "In Node Flow Zone 1",
    # ('System Node Mass Flow Rate', 'SPACE2-1 IN NODE'): "In Node Flow Zone 2",
    # ('System Node Mass Flow Rate', 'SPACE3-1 IN NODE'): "In Node Flow Zone 3",
    # ('System Node Mass Flow Rate', 'SPACE4-1 IN NODE'): "In Node Flow Zone 4",
    # ('System Node Mass Flow Rate', 'SPACE5-1 IN NODE'): "In Node Flow Zone 5",
    # Power
    ('Zone Air Terminal Sensible Cooling Energy', 'BASEMENT VAV BOX'): "Cooling Power Zone 1",
    ('Zone Air Terminal Sensible Cooling Energy', 'CORE_BOTTOM VAV BOX'): "Cooling Power Zone 2",
    ('Zone Air Terminal Sensible Cooling Energy', 'CORE_MID VAV BOX'): "Cooling Power Zone 3",
    ('Zone Air Terminal Sensible Cooling Energy', 'CORE_TOP VAV BOX'): "Cooling Power Zone 4",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_BOT_ZN_1 VAV BOX'): "Cooling Power Zone 5",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_BOT_ZN_2 VAV BOX'): "Cooling Power Zone 6",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_BOT_ZN_3 VAV BOX'): "Cooling Power Zone 7",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_BOT_ZN_4 VAV BOX'): "Cooling Power Zone 8",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_MID_ZN_1 VAV BOX'): "Cooling Power Zone 9",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_MID_ZN_2 VAV BOX'): "Cooling Power Zone 10",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_MID_ZN_3 VAV BOX'): "Cooling Power Zone 11",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_MID_ZN_4 VAV BOX'): "Cooling Power Zone 12",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_TOP_ZN_1 VAV BOX'): "Cooling Power Zone 13",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_TOP_ZN_2 VAV BOX'): "Cooling Power Zone 14",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_TOP_ZN_3 VAV BOX'): "Cooling Power Zone 15",
    ('Zone Air Terminal Sensible Cooling Energy', 'PERIMETER_TOP_ZN_4 VAV BOX'): "Cooling Power Zone 16",
    ('Zone Air Terminal Sensible Heating Energy', 'BASEMENT VAV BOX'): "Heating Power Zone 1",
    ('Zone Air Terminal Sensible Heating Energy', 'CORE_BOTTOM VAV BOX'): "Heating Power Zone 2",
    ('Zone Air Terminal Sensible Heating Energy', 'CORE_MID VAV BOX'): "Heating Power Zone 3",
    ('Zone Air Terminal Sensible Heating Energy', 'CORE_TOP VAV BOX'): "Heating Power Zone 4",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_BOT_ZN_1 VAV BOX'): "Heating Power Zone 5",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_BOT_ZN_2 VAV BOX'): "Heating Power Zone 6",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_BOT_ZN_3 VAV BOX'): "Heating Power Zone 7",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_BOT_ZN_4 VAV BOX'): "Heating Power Zone 8",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_MID_ZN_1 VAV BOX'): "Heating Power Zone 9",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_MID_ZN_2 VAV BOX'): "Heating Power Zone 10",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_MID_ZN_3 VAV BOX'): "Heating Power Zone 11",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_MID_ZN_4 VAV BOX'): "Heating Power Zone 12",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_TOP_ZN_1 VAV BOX'): "Heating Power Zone 13",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_TOP_ZN_2 VAV BOX'): "Heating Power Zone 14",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_TOP_ZN_3 VAV BOX'): "Heating Power Zone 15",
    ('Zone Air Terminal Sensible Heating Energy', 'PERIMETER_TOP_ZN_4 VAV BOX'): "Heating Power Zone 16",
    ("Fan Electric Power", "Supply Fan 1"): "Fan Power",
    # Damper
    ("Zone Air Terminal VAV Damper Position", "BASEMENT VAV BOX COMPONENT"): "Basement VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "CORE_BOTTOM VAV BOX COMPONENT"): "Core_bottom VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "CORE_MID VAV BOX COMPONENT"): "Core_mid VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "CORE_TOP VAV BOX COMPONENT"): "Core_top VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_BOT_ZN_1 VAV BOX COMPONENT"): "Perimeter_bot_zn_1 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_BOT_ZN_2 VAV BOX COMPONENT"): "Perimeter_bot_zn_2 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_BOT_ZN_3 VAV BOX COMPONENT"): "Perimeter_bot_zn_3 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_BOT_ZN_4 VAV BOX COMPONENT"): "Perimeter_bot_zn_4 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_MID_ZN_1 VAV BOX COMPONENT"): "Perimeter_mid_zn_1 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_MID_ZN_2 VAV BOX COMPONENT"): "Perimeter_mid_zn_2 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_MID_ZN_3 VAV BOX COMPONENT"): "Perimeter_mid_zn_3 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_MID_ZN_4 VAV BOX COMPONENT"): "Perimeter_mid_zn_4 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_TOP_ZN_1 VAV BOX COMPONENT"): "Perimeter_top_zn_1 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_TOP_ZN_2 VAV BOX COMPONENT"): "Perimeter_top_zn_2 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_TOP_ZN_3 VAV BOX COMPONENT"): "Perimeter_top_zn_3 VAV Damper Position",
    ("Zone Air Terminal VAV Damper Position", "PERIMETER_TOP_ZN_4 VAV BOX COMPONENT"): "Perimeter_top_zn_4 VAV Damper Position",
}

eplus_var_types = {
    'Site Outdoor Air Drybulb Temperature': "Environment",
    'Site Diffuse Solar Radiation Rate per Area': "Environment",
    'Site Direct Solar Radiation Rate per Area': "Environment",
    'Building Mean Temperature': "EMS",
    'Facility Total HVAC Electric Demand Power': 'Whole Building',
    'Building Mean PPD': "EMS",
    'Indoor Air Temperature Setpoint': "EMS",
    'Occupancy Flag': "EMS",
}

